"""
=================================================================
PLANNED vs ACTUAL PATH VISUALIZATION
Mobile Robotics M2  |  University of Salford

Standalone script — does NOT modify A* controller or Webots code.

Run:  python visualize_path.py

Reads:  astar_results.csv   (generated by contribution1_astar_v7.py)
Saves:  planned_vs_actual.png

What it shows:
  - Background : inflated C-space occupancy grid
  - Red line   : A* planned path (replicated from controller logic)
  - Green line : Actual robot trajectory from CSV (GPS positions)
  - Markers    : Start (green circle), Goal (blue star)
  - Per-run    : Individual GPS traces in different shades

Install:
    pip install numpy matplotlib scipy
=================================================================
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
from matplotlib.colors import LinearSegmentedColormap
from scipy.ndimage import binary_dilation
import heapq
import math
import csv
import os
import sys

# =================================================================
#  CONFIGURATION — must match contribution1_astar_v7.py exactly
# =================================================================

# Map geometry (GPS-relative mm)
MAP_RES_MM  = 50.0
MAP_X1      = -4360.0;  MAP_X2 =  690.0
MAP_Y1      = -5670.0;  MAP_Y2 = 3850.0
INFLATE_MM  = 220.0

# Goal (GPS-relative mm)
GOAL_X_MM   =   93.0
GOAL_Y_MM   = 2659.0

# Start (GPS origin — always 0,0 in GPS-relative frame)
START_X_MM  =    0.0
START_Y_MM  =    0.0

# Dense waypoint spacing (must match controller)
WP_SPACING  = 50.0

# Wall + obstacle bounding boxes (GPS-relative mm, from .wbt)
WALL_BOXES = [
    (  473, -5661,    673,  3839),   # East wall
    (-4327, -5671,  -4127,  3829),   # West wall
    (-4337,  3639,    663,  3839),   # North wall
    (-4360, -5670,    690, -5610),   # South boundary
    (-3127, -3081,  -2927,  1499),   # wall(5) N-S divider
    (-2997,   419,    523,   659),   # wall(6) kitchen shelf
    (-2927,   619,    473,  1319),   # wall(7) kitchen counter
    (-1772, -3231,    478, -3031),   # wall(4) corridor divider
    (-1517, -4648,  -1267, -3233),   # wall(3)
    (-2837, -4841,    663, -4641),   # wall(2) bottom
    (-2837, -5641,  -2637, -4641),   # wall(1) corner
]

OBSTACLE_BOXES = [
    (-1957, -1701,   -957,   399),   # Bed
    ( -107, -3571,    293, -2671),   # Cabinet
    (-2437,  2929,  -1187,  3629),   # Desk
    (-1587,  2009,  -1087,  2509),   # Chair 1
    (-2637,  2009,  -2137,  2509),   # Chair 2
]

# Room feature labels for annotation
ROOM_LABELS = [
    ("Bed",      -1457,  -651),
    ("Desk",     -1837,  3279),
    ("Cabinet",     93, -3121),
    ("Kitchen",  -1500,   970),
    ("Start",        0,     0),
    ("Goal",        93,  2659),
]

# CSV file path — tries current directory and parent
CSV_CANDIDATES = [
    "astar_results.csv",
    os.path.join(os.path.dirname(__file__), "astar_results.csv"),
    os.path.join(os.path.dirname(__file__), "..", "astar_results.csv"),
]

# Output file
OUTPUT_PNG = "planned_vs_actual.png"


# =================================================================
#  STEP 1 — GRID HELPERS
# =================================================================

COLS = int(math.ceil((MAP_X2 - MAP_X1) / MAP_RES_MM)) + 2   # 103
ROWS = int(math.ceil((MAP_Y2 - MAP_Y1) / MAP_RES_MM)) + 2   # 193


def world_to_grid(x_mm: float, y_mm: float):
    """GPS-relative mm → grid (col, row).  Row 0 = north (max Y)."""
    c = int(round((x_mm - MAP_X1) / MAP_RES_MM))
    r = int(round((MAP_Y2 - y_mm) / MAP_RES_MM))
    return max(0, min(COLS-1, c)), max(0, min(ROWS-1, r))


def grid_to_world(col: int, row: int):
    """Grid (col, row) → GPS-relative mm."""
    return MAP_X1 + col * MAP_RES_MM, MAP_Y2 - row * MAP_RES_MM


# =================================================================
#  STEP 2 — BUILD OCCUPANCY GRID  (same logic as controller)
# =================================================================

def build_grids():
    """
    Returns (raw_grid, inflated_grid) as np.uint8 arrays shape (ROWS, COLS).
    Identical to OccupancyGrid in contribution1_astar_v7.py.
    """
    raw = np.zeros((ROWS, COLS), dtype=np.uint8)

    def fill(x1, y1, x2, y2):
        c1, r2 = world_to_grid(min(x1,x2), min(y1,y2))
        c2, r1 = world_to_grid(max(x1,x2), max(y1,y2))
        c1, c2 = min(c1,c2), max(c1,c2)
        r1, r2 = min(r1,r2), max(r1,r2)
        raw[max(0,r1):min(ROWS,r2+1),
            max(0,c1):min(COLS,c2+1)] = 1

    for box in WALL_BOXES + OBSTACLE_BOXES:
        fill(*box)

    # Circular inflation
    rc = int(math.ceil(INFLATE_MM / MAP_RES_MM))
    yi, xi = np.ogrid[-rc:rc+1, -rc:rc+1]
    struct = (xi**2 + yi**2 <= rc**2).astype(bool)
    inflated = binary_dilation(raw.astype(bool),
                               structure=struct).astype(np.uint8)

    print(f"[GRID] {ROWS}×{COLS}  "
          f"raw={raw.sum()/raw.size*100:.1f}%  "
          f"inflated={inflated.sum()/inflated.size*100:.1f}%")
    return raw, inflated


# =================================================================
#  STEP 3 — A* + DENSE PATH  (same logic as controller)
# =================================================================

MOVES8 = [(-1,0,1.),(1,0,1.),(0,-1,1.),(0,1,1.),
          (-1,-1,1.414),(-1,1,1.414),(1,-1,1.414),(1,1,1.414)]


def _astar(inflated, sc, sr, gc, gr):
    def h(c, r):
        dx, dy = abs(gc-c), abs(gr-r)
        return max(dx,dy) + 0.414*min(dx,dy)

    heap    = [(h(sc,sr), 0., sc, sr)]
    came    = {}
    g_score = {(sc,sr): 0.}
    visited = set()

    while heap:
        _, g, c, r = heapq.heappop(heap)
        if (c,r) in visited: continue
        if c==gc and r==gr:
            path=[(c,r)]
            while (c,r) in came:
                c,r=came[(c,r)]; path.append((c,r))
            path.reverse(); return path
        visited.add((c,r))
        for dc,dr,cost in MOVES8:
            nc,nr=c+dc,r+dr
            if not(0<=nc<COLS and 0<=nr<ROWS): continue
            if inflated[nr,nc]==1 or (nc,nr) in visited: continue
            ng=g+cost
            if ng<g_score.get((nc,nr),1e18):
                g_score[(nc,nr)]=ng; came[(nc,nr)]=(c,r)
                heapq.heappush(heap,(ng+h(nc,nr),ng,nc,nr))
    return None


def _snap_free(inflated, c, r):
    if inflated[r, c] == 0:
        return c, r
    for d in range(1, 60):
        for dr in range(-d, d+1):
            for dc in range(-d, d+1):
                if max(abs(dr),abs(dc))==d:
                    nc,nr=c+dc,r+dr
                    if (0<=nc<COLS and 0<=nr<ROWS
                            and inflated[nr,nc]==0):
                        return nc, nr
    raise RuntimeError("No free cell found")


def compute_planned_path(inflated):
    """
    Recompute the dense A* path exactly as the controller does.
    Returns list of (x_mm, y_mm) GPS-relative world coordinates.
    """
    sc, sr = _snap_free(inflated, *world_to_grid(START_X_MM, START_Y_MM))
    gc, gr = _snap_free(inflated, *world_to_grid(GOAL_X_MM,  GOAL_Y_MM))

    path = _astar(inflated, sc, sr, gc, gr)
    if path is None:
        raise RuntimeError("A* found no path — check grid parameters")

    # Convert grid cells → world mm
    world = [grid_to_world(c, r) for c, r in path]

    # Dense interpolation every WP_SPACING mm (same as controller)
    dense = [world[0]]
    for i in range(len(world) - 1):
        x1, y1 = world[i]
        x2, y2 = world[i+1]
        seg = math.hypot(x2-x1, y2-y1)
        if seg <= WP_SPACING:
            dense.append((x2, y2))
        else:
            n = int(math.ceil(seg / WP_SPACING))
            for k in range(1, n+1):
                t = k / n
                dense.append((x1+t*(x2-x1), y1+t*(y2-y1)))

    length = sum(math.hypot(dense[i+1][0]-dense[i][0],
                            dense[i+1][1]-dense[i][1])
                 for i in range(len(dense)-1))
    print(f"[PATH] {len(path)} cells → {len(dense)} dense waypoints  "
          f"{length/1000:.2f} m")
    return dense


# =================================================================
#  STEP 4 — LOAD CSV
# =================================================================

def load_csv():
    """
    Load astar_results.csv.

    CSV columns (from contribution1_astar_v7.py):
      run, event, mode, x_mm, y_mm, th_deg,
      goal_x_mm, goal_y_mm, error_mm,
      time_s, path_mm, n_waypoints, plan_ms

    Returns:
      runs_dict : {run_id: [(x_mm, y_mm, time_s, event), ...]}
      all_pts   : [(x_mm, y_mm), ...] all positions across all runs
    """
    csv_path = None
    for candidate in CSV_CANDIDATES:
        if os.path.isfile(candidate):
            csv_path = candidate
            break

    if csv_path is None:
        print("[CSV] WARNING: astar_results.csv not found in:")
        for c in CSV_CANDIDATES:
            print(f"        {c}")
        print("[CSV] Plotting planned path only (no actual trajectory).")
        return {}, []

    print(f"[CSV] Loading: {csv_path}")
    runs_dict = {}
    all_pts   = []

    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)

        # Normalise column names (strip whitespace)
        reader.fieldnames = [n.strip() for n in (reader.fieldnames or [])]

        for row in reader:
            try:
                run    = int(row.get("run", 0))
                event  = row.get("event", "").strip()
                x_mm   = float(row.get("x_mm",   row.get("x", 0)))
                y_mm   = float(row.get("y_mm",   row.get("y", 0)))
                t_s    = float(row.get("time_s", 0))

                if run not in runs_dict:
                    runs_dict[run] = []
                runs_dict[run].append((x_mm, y_mm, t_s, event))
                all_pts.append((x_mm, y_mm))
            except (ValueError, KeyError):
                continue   # skip header / bad rows

    n_runs = len(runs_dict)
    n_pts  = len(all_pts)
    print(f"[CSV] Loaded {n_pts} rows across {n_runs} run(s)")
    for run_id, pts in sorted(runs_dict.items()):
        events = [e for _,_,_,e in pts]
        print(f"       Run {run_id}: {len(pts)} points  "
              f"events={events}")
    return runs_dict, all_pts


# =================================================================
#  STEP 5 — BUILD DISPLAY IMAGES
# =================================================================

def make_grid_rgb(raw, inflated):
    """
    Build an RGB image for the occupancy grid background.
      White       = free space
      Light grey  = inflated margin
      Dark grey   = actual wall/obstacle
    """
    h, w = raw.shape
    rgb  = np.ones((h, w, 3), dtype=float)

    # Inflated margin (where raw=0 but inflated=1)
    margin_mask          = (inflated == 1) & (raw == 0)
    rgb[margin_mask]     = [0.72, 0.72, 0.76]

    # Actual wall / obstacle
    wall_mask            = (raw == 1)
    rgb[wall_mask]       = [0.18, 0.18, 0.20]

    # Flip so y increases upward in the plot
    return np.flipud(rgb)


# =================================================================
#  STEP 6 — MAIN VISUALIZATION
# =================================================================

def visualize(raw, inflated, planned_pts, runs_dict):
    """
    THREE-PANEL FIGURE (matches reference image style):

      Panel 1 — Raw Grid (Before Inflation)
                Black = wall/obstacle,  White = free space
                Grid axis labels show cell indices

      Panel 2 — Inflated Grid (Configuration Space)
                Black = obstacle + inflated margin,  White = free
                Grid axis labels show cell indices

      Panel 3 — Planned vs Actual Robot Path
                Background: inflated C-space
                Red line   = A* planned path
                Green line = Actual GPS trajectory
                Start = green circle,  Goal = blue star

    All three use equal axis scaling and grid index axes.
    """

    run_colors = [
        "#00dd77",   # run 1 — bright green
        "#00aa55",   # run 2
        "#007733",   # run 3
        "#004d22",   # run 4
        "#33ff99",   # run 5
    ]

    # ── Figure layout: 3 panels side by side ─────────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(22, 14))
    fig.patch.set_facecolor("white")
    fig.suptitle(
        "A* Path Planning — Raw Grid, Configuration Space & Planned vs Actual Path\n"
        f"Mobile Robotics M2  |  University of Salford  |  "
        f"Grid: {ROWS}×{COLS} cells  |  res={MAP_RES_MM:.0f}mm  |  inflate={INFLATE_MM:.0f}mm",
        fontsize=12, fontweight="bold", color="black", y=1.01
    )

    # ── Helper: style each axis with white background + grid index labels ─
    def style_ax(ax, title):
        ax.set_facecolor("white")
        ax.set_title(title, fontsize=12, fontweight="bold",
                     color="black", pad=8)
        ax.set_xlabel("Column index  (cells)", fontsize=9, color="#333333")
        ax.set_ylabel("Row index  (cells)",    fontsize=9, color="#333333")
        ax.tick_params(colors="#333333", labelsize=8)
        for sp in ax.spines.values():
            sp.set_edgecolor("#aaaaaa")
            sp.set_linewidth(0.8)

    # ── PANEL 1: Raw Grid (Before Inflation) ─────────────────────────────
    ax1 = axes[0]
    # imshow with origin="upper" so row 0 is at the top (matches image)
    ax1.imshow(raw, cmap="binary", origin="upper",
               interpolation="nearest", aspect="equal",
               vmin=0, vmax=1)
    style_ax(ax1, "Raw Grid (Before Inflation)")

    # Mark start and goal as small dots
    sc, sr = world_to_grid(START_X_MM, START_Y_MM)
    gc, gr = world_to_grid(GOAL_X_MM,  GOAL_Y_MM)
    ax1.plot(sc, sr, "o", color="#00cc55", markersize=9,
             markeredgecolor="black", markeredgewidth=0.8,
             zorder=5, label="Start")
    ax1.plot(gc, gr, "*", color="#0088ff", markersize=13,
             markeredgecolor="black", markeredgewidth=0.5,
             zorder=5, label="Goal")
    ax1.legend(loc="upper right", fontsize=8,
               facecolor="white", edgecolor="#aaaaaa")

    # ── PANEL 2: Inflated Grid (Configuration Space) ──────────────────────
    ax2 = axes[1]
    ax2.imshow(inflated, cmap="binary", origin="upper",
               interpolation="nearest", aspect="equal",
               vmin=0, vmax=1)
    style_ax(ax2, "Inflated Grid (Configuration Space)")

    ax2.plot(sc, sr, "o", color="#00cc55", markersize=9,
             markeredgecolor="black", markeredgewidth=0.8, zorder=5)
    ax2.plot(gc, gr, "*", color="#0088ff", markersize=13,
             markeredgecolor="black", markeredgewidth=0.5, zorder=5)

    # ── PANEL 3: Planned vs Actual Path ───────────────────────────────────
    ax3 = axes[2]

    # Background: inflated grid (black = obstacle, white = free)
    ax3.imshow(inflated, cmap="binary", origin="upper",
               interpolation="nearest", aspect="equal",
               vmin=0, vmax=1, zorder=0)
    style_ax(ax3, "Planned vs Actual Robot Path")

    # Planned A* path — convert world mm → grid indices
    if planned_pts:
        path_cols = [(world_to_grid(p[0], p[1])[0]) for p in planned_pts]
        path_rows = [(world_to_grid(p[0], p[1])[1]) for p in planned_pts]
        path_len  = sum(
            math.hypot(planned_pts[i+1][0]-planned_pts[i][0],
                       planned_pts[i+1][1]-planned_pts[i][1])
            for i in range(len(planned_pts)-1)
        )
        ax3.plot(path_cols, path_rows,
                 color="red", linewidth=1.8, zorder=3,
                 label=f"A* planned path  "
                       f"({len(planned_pts)} wps, {path_len/1000:.2f}m)")

    # Actual trajectories — per run
    for run_id, pts in sorted(runs_dict.items()):
        if not pts:
            continue
        traj_c = [world_to_grid(p[0], p[1])[0] for p in pts]
        traj_r = [world_to_grid(p[0], p[1])[1] for p in pts]
        color  = run_colors[(run_id-1) % len(run_colors)]
        ax3.plot(traj_c, traj_r,
                 color=color, linewidth=2.2,
                 zorder=4, alpha=0.9,
                 label=f"Actual trajectory  run {run_id}")

        # Direction arrows
        step = max(1, len(traj_c) // 8)
        for i in range(0, len(traj_c)-1, step):
            dc_ = traj_c[i+1] - traj_c[i]
            dr_ = traj_r[i+1] - traj_r[i]
            if abs(dc_)+abs(dr_) > 0.5:
                ax3.annotate("",
                    xy=(traj_c[i]+dc_*0.6, traj_r[i]+dr_*0.6),
                    xytext=(traj_c[i], traj_r[i]),
                    arrowprops=dict(arrowstyle="->",
                                   color=color, lw=1.1),
                    zorder=5)

    # Start / goal markers
    ax3.plot(sc, sr, "o", color="#00cc55", markersize=12,
             markeredgecolor="white", markeredgewidth=1.2,
             zorder=6, label=f"Start ({START_X_MM:.0f},{START_Y_MM:.0f})mm")
    ax3.plot(gc, gr, "*", color="#0088ff", markersize=16,
             markeredgecolor="white", markeredgewidth=0.8,
             zorder=6, label=f"Goal ({GOAL_X_MM:.0f},{GOAL_Y_MM:.0f})mm")

    # Room labels (in grid-index space)
    skip = {"Start", "Goal"}
    for lbl, x_mm, y_mm in ROOM_LABELS:
        if lbl in skip:
            continue
        lc, lr = world_to_grid(x_mm, y_mm)
        ax3.text(lc, lr, lbl,
                 fontsize=7, color="white", ha="center", va="center",
                 zorder=7,
                 bbox=dict(boxstyle="round,pad=0.2",
                           fc="#222255", ec="#8888cc",
                           lw=0.6, alpha=0.80))

    # Error annotation for run 1
    if 1 in runs_dict and runs_dict[1]:
        last  = runs_dict[1][-1]
        lc, lr = world_to_grid(last[0], last[1])
        err_mm = math.hypot(last[0]-GOAL_X_MM, last[1]-GOAL_Y_MM)
        ax3.annotate(f"Final err\n{err_mm:.0f} mm",
                     xy=(lc, lr),
                     xytext=(lc+5, lr+8),
                     fontsize=8, color="#ffcc00",
                     arrowprops=dict(arrowstyle="->",
                                    color="#ffcc00", lw=1.0),
                     bbox=dict(boxstyle="round,pad=0.2",
                               fc="#332200", ec="#ffcc00",
                               lw=0.7, alpha=0.88),
                     zorder=8)

    ax3.legend(loc="lower right", fontsize=8,
               facecolor="white", edgecolor="#aaaaaa",
               labelcolor="black", framealpha=0.92)

    # ── Save ──────────────────────────────────────────────────────────────
    plt.tight_layout(pad=1.5)
    plt.savefig(OUTPUT_PNG, dpi=180, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    print(f"\n[SAVED] {OUTPUT_PNG}")
    plt.show()


# =================================================================
#  STEP 7 — STATISTICS SUMMARY
# =================================================================

def print_statistics(runs_dict, planned_pts):
    """Print a summary table matching the assignment report format."""
    if not planned_pts:
        return

    planned_len = sum(
        math.hypot(planned_pts[i+1][0]-planned_pts[i][0],
                   planned_pts[i+1][1]-planned_pts[i][1])
        for i in range(len(planned_pts)-1)
    )
    straight = math.hypot(GOAL_X_MM - START_X_MM,
                          GOAL_Y_MM - START_Y_MM)

    print("\n" + "="*60)
    print("  PATH STATISTICS")
    print("="*60)
    print(f"  Planned path length : {planned_len/1000:.3f} m")
    print(f"  Straight-line dist  : {straight/1000:.3f} m")
    print(f"  Detour factor       : {planned_len/straight:.2f}×")
    print(f"  Dense waypoints     : {len(planned_pts)}")
    print(f"  Spacing             : {WP_SPACING:.0f} mm")

    if not runs_dict:
        print("\n  No actual run data found.")
        return

    print(f"\n  ACTUAL RUNS  (from astar_results.csv)")
    print(f"  {'Run':>4}  {'Points':>7}  {'Final X':>9}  "
          f"{'Final Y':>9}  {'Error mm':>10}")
    print(f"  {'-'*4}  {'-'*7}  {'-'*9}  {'-'*9}  {'-'*10}")

    errors = []
    for run_id, pts in sorted(runs_dict.items()):
        if not pts:
            continue
        fx, fy = pts[-1][0], pts[-1][1]
        err = math.hypot(fx - GOAL_X_MM, fy - GOAL_Y_MM)
        errors.append(err)
        print(f"  {run_id:>4}  {len(pts):>7}  "
              f"{fx:>9.1f}  {fy:>9.1f}  {err:>10.1f}")

    if len(errors) > 1:
        mu  = sum(errors) / len(errors)
        sig = math.sqrt(sum((e-mu)**2 for e in errors) / (len(errors)-1))
        print(f"  {'─'*50}")
        print(f"  Mean error   : {mu:.1f} mm")
        print(f"  Std deviation: {sig:.1f} mm")
        print(f"  Min error    : {min(errors):.1f} mm")
        print(f"  Max error    : {max(errors):.1f} mm")

    print("="*60)


# =================================================================
#  MAIN
# =================================================================

def main():
    print("="*60)
    print("  PLANNED vs ACTUAL PATH VISUALIZATION")
    print("  Mobile Robotics M2  |  University of Salford")
    print("="*60)
    print(f"  Grid   : {ROWS}×{COLS}  res={MAP_RES_MM:.0f}mm/cell")
    print(f"  Room   : {(MAP_X2-MAP_X1)/1000:.2f}m × {(MAP_Y2-MAP_Y1)/1000:.2f}m")
    print(f"  Start  : ({START_X_MM:.0f}, {START_Y_MM:.0f}) mm")
    print(f"  Goal   : ({GOAL_X_MM:.0f}, {GOAL_Y_MM:.0f}) mm")
    print()

    # 1. Build grids
    raw, inflated = build_grids()

    # 2. Compute planned A* path
    print("[PATH] Computing planned A* path...")
    try:
        planned = compute_planned_path(inflated)
    except RuntimeError as e:
        print(f"[ERROR] {e}")
        sys.exit(1)

    # 3. Load CSV
    runs_dict, _ = load_csv()

    # 4. Print statistics
    print_statistics(runs_dict, planned)

    # 5. Visualize
    print("\n[PLOT] Generating figure...")
    visualize(raw, inflated, planned, runs_dict)

    print("[DONE]")


if __name__ == "__main__":
    main()